---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: inList
  labels:
    app: inList
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inList
  template:
    metadata:
      labels:
        app: inList
    spec:
      containers:
        - name: inList
          image: username/inList:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext602
  labels:
    app: BoundedContext602
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext602
  template:
    metadata:
      labels:
        app: BoundedContext602
    spec:
      containers:
        - name: BoundedContext602
          image: username/BoundedContext602:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: inList
  labels:
    app: inList
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: inList


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext602
  labels:
    app: BoundedContext602
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext602

